import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import Link from 'next/link';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} flex flex-col h-screen overflow-hidden`}
			>
				<header className='flex items-center justify-between p-6 bg-white  dark:bg-gray-800 shadow-md'>
					<div className='flex items-center space-x-4'>
						<h1 className='text-lg font-semibold text-gray-800 dark:text-gray-200'>
							<span className='text-2xl'>Self</span>, your life at a glance
						</h1>
					</div>
					<nav className='flex items-center space-x-6'>
						{/* <Link
						className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
						href='#'
					>
						Upload
					</Link>
					<Link
						className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
						href='#'
					>
						Output
					</Link>
					<Link
						className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
						href='#'
					>
						Events
					</Link> */}
						<Link
							className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
							href='#'
						>
							<div className='flex items-center space-x-2 gap-2 rounded-lg'>
								<Avatar>
									<AvatarImage
										src='https://github.com/dhimiterPoison.png'
										alt='@dhimiterPoison'
									/>
									<AvatarFallback>DH</AvatarFallback>
								</Avatar>
								D. Helmi
							</div>
						</Link>
					</nav>
				</header>
				{children}
				<Analytics></Analytics>
			</body>
		</html>
	);
}
