import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import Link from 'next/link';
import { Analytics } from '@vercel/analytics/react';
import { Button } from '@/components/ui/button';

const inter = Inter({ subsets: ['latin'] });
const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Self - glance',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`${inter.className} flex flex-col h-screen overflow-hidden`}
			>
				<header className='flex w-full h-20 items-center justify-between p-6 bg-gradient-to-b from-white  to-[#a8abad] fade dark:bg-gray-800 shadow-md'>
					<div className='flex items-center space-x-4'>
						<h1
							className={`text-lg font-semibold text-gray-800 dark:text-gray-200 ${manrope.className}`}
						>
							<Link href="/" className='flex items-end'><span className='text-2xl'>Self</span><span className='hidden md:flex'>, your life at a glance</span></Link>
						</h1>
					</div>
					<nav className='flex items-center space-x-6'>
						{/* <Link
						className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
						href='#'
					>
						Upload
					</Link>
					<Link
						className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
						href='#'
					>
						Output
					</Link>*/}
					<Link
						className='hover:text-gray-800 dark:hover:text-gray-200 hover:underline'
						href='#'
					>
						Mission
					</Link> 
						{/* <Link
							className='text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200'
							href='#'
						>
							<div className='flex items-center space-x-2 gap-2 rounded-lg'>
								<Avatar>
									<AvatarImage
										src='https://github.com/dhimiterPoison.png'
										alt='@dhimiterPoison'
									/>
									<AvatarFallback>DH</AvatarFallback>
								</Avatar>
								D. Helmi
							</div>
						</Link> */}
						<Button className='rounded-full'><Link href="/dashboard">Try it out</Link></Button>
					</nav>
				</header>
				{children}
				<Analytics></Analytics>
			</body>
		</html>
	);
}
